### ISSUE TITLE
When using the new LoRa view option, console shows an invalid file line and the preview image does not load

### ISSUE THREAD

**Issue by rushtothesun** [Haoming02/sd-webui-easy-tag-insert#13]
`[EZ Tags] Invalid File: "L:\A1111\extensions\sd-webui-easy-tag-insert\cards\Cards\Grass.preview.png"`

The preview image will only load if you click on the tools icon and click "Replace Preview." If you restart the webui you have to do it again.

![bug](https://github.com/Haoming02/sd-webui-easy-tag-insert/assets/20650932/af9728b1-9f79-41b8-b48d-1f66395464da)

**Comment by Haoming02** [comment]
Yeah, IDK why the preview isn't loading automatically... 

I'mma try looking around.

**Comment by Haoming02** [comment]
Should be fixed now~

**Comment by rushtothesun** [comment]
Issue fixed, appreciate it!
