### ISSUE TITLE
Please give some examples

### ISSUE THREAD

**Issue by Ypdes** [Haoming02/sd-webui-easy-tag-insert#2]
Hi, thanks for your extension. It's really interesting. I'm sorry, but I don't understand, how to add tags. Could you please add some examples to your manual. Ex.: I have lora with these triggers: perfect hands. How can I use them with youe extension? Where can I find the button (which you wrote).
Thank you

**Comment by Haoming02** [comment]
After you launch the webui with this Extension installed, there should be a folder here: `~\stable-diffusion-webui\extensions\sd-webui-easy-tag-insert\tags`

You can just edit the sample file, and add the entry of your chioce.
Such as:
```yaml
  Hands: perfect hands, <lora:your lora name:1.0>
```

**Comment by Ypdes** [comment]
And then? How can I insert them?

**Comment by Haoming02** [comment]
Have you launched the webui yet...?

**Comment by Ypdes** [comment]
Yes I have

**Comment by Haoming02** [comment]
Then you should see the buttons?

**Comment by Ypdes** [comment]
Where?

**Comment by Haoming02** [comment]
Send a screenshot

**Comment by Ypdes** [comment]
![image](https://github.com/Haoming02/sd-webui-easy-tag-insert/assets/134853152/b1ef0ac4-aeb6-4f7a-9586-d9d88927e983)

**Comment by Haoming02** [comment]
Have you Reload UI after installing the Extension?

**Comment by Ypdes** [comment]
Sure, I installed it and pressed Apply after that. Here is:

![image](https://github.com/Haoming02/sd-webui-easy-tag-insert/assets/134853152/f344b90d-4907-40c6-b920-40e5fe29840c)

**Comment by Haoming02** [comment]
Is there any error in the Console?

**Comment by Ypdes** [comment]
Is this important?

*** Error executing callback before_ui for D:\Soft\Design\AI\StableDiffusion\SD_portable\stable-diffusion-portable-main\extensions\sd-webui-easy-tag-insert\scripts\eztags.py

**Comment by Haoming02** [comment]
Yes

**Comment by Haoming02** [comment]
Probably related, if the error log you didn't include is about the same problem

**Comment by Haoming02** [comment]
Assuming it's the same issue, which has been fixed~
