### ISSUE TITLE
Whole extension Folder gets cleansed

### ISSUE THREAD

**Issue by Nu70ry** [Haoming02/sd-webui-easy-tag-insert#8]
Added the default tags that come with this extension in a new Folder and created my own folder structure with tags.
But this extension Cleanse the whole extension Folder, that's always a bad way to delete all the saved tags of the user.
if it's an user error, cleanse the whole folder is still just bad.
Even if you handle this extension correct, 1 misstake and it cleanse all your tags.

**Comment by Haoming02** [comment]
Hmm, but it doesn't even touch the `tags` folder at all after it's been created though?
