### ISSUE TITLE
[Feature Request] Choose sides to insert

### ISSUE THREAD

**Issue by enternalsaga** [Haoming02/sd-webui-easy-tag-insert#9]
Hi,
Similar to [StyleSelectorXL](https://github.com/ahgsql/StyleSelectorXL) can you update to choose position in prompt to add.
![image](https://github.com/Haoming02/sd-webui-easy-tag-insert/assets/31148570/53de7b95-0c7d-4086-822c-4b65e726dfe7)

**Comment by Haoming02** [comment]
Since this is using the same built-in logics as **LoRA**s or **Textual Inversion**s, I don't think that would be possible unfortunately...

**Comment by enternalsaga** [comment]
Never mind! i just found out normal style feature can actually work with {prompt} as syntax. Never thought it could work before until try! closing now.
